name: dyebo
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - matplotlib
  - h5py
  - pandas
  - numpy
  - gpy
  - scikit-learn
  - protobuf
  - openpyxl
  - requests
  - seaborn
  - pip:
      - scipydirect
